// <auto-generated />
using Conembador.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Conembador.Migrations
{
    [DbContext(typeof(ConembadorContext))]
    [Migration("20240515232035_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Conembador.Models.Arquivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeEdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Versao")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Arquivos");
                });

            modelBuilder.Entity("Conembador.Models.Itens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Descricao")
                        .HasColumnType("float");

                    b.Property<int>("Fim")
                        .HasColumnType("int");

                    b.Property<int>("Id_Arquivo")
                        .HasColumnType("int");

                    b.Property<int>("Inicio")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_Arquivo");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("Conembador.Models.Itens", b =>
                {
                    b.HasOne("Conembador.Models.Arquivo", null)
                        .WithMany("ItensArquivo")
                        .HasForeignKey("Id_Arquivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Conembador.Models.Arquivo", b =>
                {
                    b.Navigation("ItensArquivo");
                });
#pragma warning restore 612, 618
        }
    }
}
